version: '2'

networks:
  fish-network:
    driver: bridge
    name: fish-network

services:
  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    networks:
      - fish-network
    volumes:
      - /home/element/dados/tutorials/nodejs/fish_wiki/redis-persistence:/data
#      - /home/element/dados/tutorials/nodejs/fish_wiki/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
